StartupEvents.registry('item', event => {

	//Register new items hete
	event.create('stone_gear').displayName('Stone Gear')
	event.create('personal_id').displayName('§9Personal ID Card')
	event.create('blank_card').displayName('Blank Card')
	event.create('blank_disk').displayName('Blank Disk')
	event.create('explorershat').displayName(`§2Explorer's Hat`)
	event.create('note_1').displayName('§e1 Dollar')
	event.create('note_2').displayName('§e2 Dollars')
	event.create('note_5').displayName('§e5 Dollars')
	event.create('note_10').displayName('§e10 Dollars')
	event.create('note_20').displayName('§e20 Dollars')
	event.create('note_50').displayName('§e50 Dollars')
	event.create('note_100').displayName('§e100 Dollars')
	event.create('note_200').displayName('§e200 Dollars')
	event.create('note_500').displayName('§e500 Dollars')
	event.create('note_1000').displayName('§e1000 Dollars')
	event.create('1b_card').displayName('§d1B Card')
	event.create('1m_card').displayName('§d1M Card')
	event.create('5k_card').displayName('§d5K Card')
	event.create('5m_card').displayName('§d5M Card')
	event.create('10k_card').displayName('§d10K Card')
	event.create('10m_card').displayName('§d10M Card')
	event.create('50k_card').displayName('§d50K Card')
	event.create('50m_card').displayName('§d50M Card')
	event.create('100k_card').displayName('§d100K Card')
	event.create('100m_card').displayName('§d100M Card')
	event.create('500k_card').displayName('§d500K Card')
	event.create('500m_card').displayName('§d500M Card')
	event.create('angerite').displayName(`§bAngerite`)
	event.create('blood_quartz').displayName(`§bBlood Quartz`)
	event.create('borgium').displayName(`§bBorgium`)
	event.create('catseye').displayName(`§bCatseye`)
	event.create('chalcanthite').displayName(`§bChalcanthite`)
	event.create('citrine').displayName(`§bCitrine`)
	event.create('corrupted_crystal').displayName(`§bCorrupted Crystal`)
	event.create('cyber_orb').displayName(`§bCyber Orb`)
	event.create('draconium_scrap').displayName(`§bDraconium Scrap`)
	event.create('eclipse_diamond').displayName(`§bEclipse Diamond`)
	event.create('fire_opal').displayName(`§bFire Opal`)
	event.create('ghoul_quartz').displayName(`§bGhoul Quartz`)
	event.create('grindstone_scrap').displayName(`§bGrindstone Scrap`)
	event.create('hercynite').displayName(`§bHercynite`)
	event.create('humoranium').displayName(`§bHumoranium`)
	event.create('matrix_opal').displayName(`§bMatrix Opal`)
	event.create('medusa_quartz').displayName(`§bMedusa Quartz`)
	event.create('meteorite_scrap').displayName(`§bMeteorite Scrap`)
	event.create('neonium').displayName(`§bNeonium`)
	event.create('cursed_crystal').displayName(`§bCursed Crystal`)
	event.create('star_sapphire').displayName(`§bStar Sapphire`)
	event.create('crystal_of_summoning').displayName(`§5Crystal of Summoning`)

})

StartupEvents.registry('block', event => {
	
	//Register new blocks here
	event.create('magical_soil').displayName('§dMagical Soil').material('grass').hardness(0.6)
	event.create('ender_pearl_block_1x').displayName('Ender Pearl Block 1x')
	event.create('ender_pearl_block_2x').displayName('Ender Pearl Block 2x')
	event.create('ender_pearl_block_3x').displayName('Ender Pearl Block 3x')
	event.create('ender_pearl_block_4x').displayName('Ender Pearl Block 4x')
	event.create('ender_pearl_block_5x').displayName('Ender Pearl Block 5x')
	event.create('ender_pearl_block_6x').displayName('Ender Pearl Block 6x')
	event.create('ender_pearl_block_7x').displayName('Ender Pearl Block 7x')
	event.create('ender_pearl_block_8x').displayName('Ender Pearl Block 8x')
	event.create('ender_pearl_block_9x').displayName('Ender Pearl Block 9x')

})
