
#Glazing Tool settings
[glazing_tool]
	# Let the glazing tool drop panes (like silk touch) by sneaking while in BREAK mode
	glazing_tool_break_pane = false
	# Allow glazing tool to mark glass panes as unbreakable while in UNBREAKING mode
	unbreakable_pane = false
	# Inhibit block rotation if marked as UNBREAKABLE
	unrotatable_pane = true

